### ISSUE TITLE
Consider using `microblog_head.html`

### ISSUE THREAD

**Issue by svendahlstrand** [jimmitchell/mnml#1]
Hey Jim and thanks for building this theme. I was wondering if you'd consider using the official Micro.blog partial, [`microblog_head.html`](https://github.com/microdotblog/theme-blank/blob/master/layouts/partials/microblog_head.html).

Right now, some Micro.blog plug-ins don't work for users of the mnml theme. By including this partial in the site's `head`section, you'd add full support for plug-ins.

Here's the code snippet:

`{{ partial "microblog_head.html" . }}`

For reference, you can see how it's used in the [Sumo theme](https://github.com/MattSLangford/Sumo-Theme/blob/main/layouts/partials/head.html#L39).

If you decide to integrate this, you could also simplify your current [`head.html`](https://github.com/jimmitchell/mnml/blob/main/layouts/partials/head.html) file, as `microblog_head.html` would handle some of the existing functionality for you.

Thanks again for all your work on the theme!

**Comment by jimmitchell** [comment]
Thanks, Sven. I will address this as soon as possible. Appreciate you letting me know about it.

**Comment by jimmitchell** [comment]
> Right now, some Micro.blog plug-ins don't work for users of the mnml theme. By including this partial in the site's `head`section, you'd add full support for plug-ins.

@svendahlstrand do you have an example of a plugin that was not working, so I can test?

**Comment by svendahlstrand** [comment]
Wow, that was quick. My own plug-in, Faviconique, is one example. I tried it just now with your latest changes, and it works like a charm. Thanks!

**Comment by jimmitchell** [comment]
Closed/fixed v2.0.7
